
# This is a basic workflow to help you get started with Actions
name: Docker CI-CD

# Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#     paths:
#       - '**.js'
#   pull_request:
#     branches: [ main ]
#     paths:
#       - '**.js'

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  push_to_Docker_Hub:

      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x, 15.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - run: npm ci
        - run: npm run build --if-present

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.Docker_username }}
            password: ${{ secrets.Docker_password }}

        - name: Get current date
          id: getDate
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

        - name: Get semantic version from file
          id: getSemver
          run: echo "::set-output name=semver::$(cat VERSION | tr -d ' \t\n\r' )"
      
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            platforms: linux/amd64,linux/arm64,linux/arm/v7
            tags: |
              dmatik/oref-alerts:latest
              dmatik/oref-alerts:${{ steps.getSemver.outputs.semver }}
            build-args: |
              VCS_REF=${{ github.sha }}
              BUILD_DATE=${{ steps.getDate.outputs.date }}
              VERSION=${{ steps.getSemver.outputs.semver }}
          